### ISSUE TITLE
How to restrict couchbase access to only localhost

### ISSUE THREAD

**Issue by timur1988** [couchbase/build-tools#13]
How to restrict couchbase access to only localhost?

**Comment by ceejatec** [comment]
This repository is for build scripts and related tools for Couchbase (the company). For operating questions about Couchbase Server or other products, community support is provided via the forums: https://forums.couchbase.com/

As for your specific question, I'm afraid I don't know if there is a specific way to configure it to listen only on localhost. Couchbase Server communicates on a large number of network ports and is normally intended to be used in a cluster, so such a configuration wouldn't be generally useful. If you need it for a single-node test environment, my suggestion would be either:
* Run Couchbase in a Docker container, exposing only the ports you need and binding them to localhost. For instance, the primary UI port is 8091, so something like this works:
```
docker run -d -p 127.0.0.1:8091:8091 couchbase/server:7.0.3
```
* Investigate using iptables to limit external access to your VM.
